### ISSUE TITLE
Set up vetting tools

### ISSUE THREAD

**Issue by ericcornelissen** [ericcornelissen/eslint-plugin-top#124]
### Summary

Start using tooling to vet the source code for bad practices. This is closely related to linting, but different in that it's concerned with things that are not about source code formatting in any way (whether stylistic or "code smells").

Candidate tools (in alphabetical order):
- [x] [depcheck](https://www.npmjs.com/package/depcheck): Find unused dependencies.
- [x] [knip](https://www.npmjs.com/package/knip): Find unused files, dependencies and exports.
- [x] [type-coverage](https://www.npmjs.com/package/type-coverage): Ensure TypeScript is used to it's fullest extend.
- [x] [unimported](https://www.npmjs.com/package/unimported): Find unused source files.
